apiVersion: apps/v1 
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: akhileshappala11/donorservice:amd64 #MAY BE INCORRECT
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
            protocol: TCP
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: PARENT_DB
            value: "freeFood"
          - name: USER_FLASK_PORT
            value: "8081"
          
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 8081
  type: LoadBalancer  
